-- +goose Up
-- +goose StatementBegin
INSERT INTO permissions (code, module, action, description) VALUES
  ('dashboard-read', 'dashboard', 'read', 'Melihat halaman dashboard'),
  ('employee-read', 'employee', 'read', 'Melihat daftar dan detail pegawai'),
  ('employee-create', 'employee', 'create', 'Menambah data pegawai baru'),
  ('employee-update', 'employee', 'update', 'Memperbarui data pegawai'),
  ('employee-delete', 'employee', 'delete', 'Menghapus data pegawai'),
  ('branch-read', 'branch', 'read', 'Melihat daftar cabang'),
  ('branch-create', 'branch', 'create', 'Menambah data cabang baru'),
  ('branch-update', 'branch', 'update', 'Memperbarui data cabang'),
  ('branch-delete', 'branch', 'delete', 'Menghapus data cabang'),
  ('department-read', 'department', 'read', 'Melihat daftar departemen'),
  ('department-create', 'department', 'create', 'Menambah data departemen baru'),
  ('department-update', 'department', 'update', 'Memperbarui data departemen'),
  ('department-delete', 'department', 'delete', 'Menghapus data departemen'),
  ('position-read', 'position', 'read', 'Melihat daftar jabatan'),
  ('position-create', 'position', 'create', 'Menambah data jabatan baru'),
  ('position-update', 'position', 'update', 'Memperbarui data jabatan'),
  ('position-delete', 'position', 'delete', 'Menghapus data jabatan'),
  ('role-read', 'role', 'read', 'Melihat daftar peran dan hak akses'),
  ('role-create', 'role', 'create', 'Menambah peran baru'),
  ('role-update', 'role', 'update', 'Memperbarui peran dan hak akses'),
  ('role-delete', 'role', 'delete', 'Menghapus peran'),
  ('leave_type-read', 'leave_type', 'read', 'Melihat tipe cuti'),
  ('leave_type-create', 'leave_type', 'create', 'Menambah tipe cuti baru'),
  ('leave_type-update', 'leave_type', 'update', 'Memperbarui tipe cuti'),
  ('leave_type-delete', 'leave_type', 'delete', 'Menghapus tipe cuti'),
  ('shift-read', 'shift', 'read', 'Melihat jadwal shift'),
  ('shift-create', 'shift', 'create', 'Menambah jadwal shift baru'),
  ('shift-update', 'shift', 'update', 'Memperbarui jadwal shift'),
  ('shift-delete', 'shift', 'delete', 'Menghapus jadwal shift'),
  ('holiday-read', 'holiday', 'read', 'Melihat daftar hari libur'),
  ('holiday-create', 'holiday', 'create', 'Menambah hari libur baru'),
  ('holiday-update', 'holiday', 'update', 'Memperbarui hari libur'),
  ('holiday-delete', 'holiday', 'delete', 'Menghapus hari libur'),
  ('attendance-read', 'attendance', 'read', 'Melihat data presensi'),
  ('attendance-create', 'attendance', 'create', 'Melakukan presensi manual'),
  ('attendance-update', 'attendance', 'update', 'Memperbarui atau menyetujui presensi'),
  ('leave-read', 'leave', 'read', 'Melihat daftar pengajuan cuti'),
  ('leave-create', 'leave', 'create', 'Membuat pengajuan cuti'),
  ('leave-update', 'leave', 'update', 'Menyetujui atau menolak cuti'),
  ('request-read', 'request', 'read', 'Melihat daftar permohonan'),
  ('request-create', 'request', 'create', 'Membuat permohonan baru'),
  ('request-update', 'request', 'update', 'Menyetujui atau menolak permohonan'),
  ('daily_report-read', 'daily_report', 'read', 'Melihat laporan harian'),
  ('daily_report-create', 'daily_report', 'create', 'Membuat laporan harian'),
  ('daily_report-update', 'daily_report', 'update', 'Memperbarui laporan harian'),
  ('mutabaah-read', 'mutabaah', 'read', 'Melihat log mutabaah'),
  ('mutabaah-create', 'mutabaah', 'create', 'Membuat log mutabaah'),
  ('mutabaah-update', 'mutabaah', 'update', 'Memperbarui log mutabaah');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
TRUNCATE permissions RESTART IDENTITY CASCADE;
-- +goose StatementEnd
