-- +goose Up
-- +goose StatementBegin
INSERT INTO permissions (code, module, action, description) VALUES
  ('home-employee_read',              'home',                   'employee_read',     'Melihat halaman home pegawai'),
  ('home-admin_read',                 'home',                   'admin_read',        'Melihat halaman home admin'),
  ('home-clock_in',                   'home',                   'clock_in',          'Melakukan clock in di halaman home'),
  ('home-clock_out',                  'home',                   'clock_out',         'Melakukan clock out di halaman home'),
  ('employee-read',                   'employee',               'read',              'Melihat data pegawai'),
  ('employee-create',                 'employee',               'create',            'Membuat data pegawai'),
  ('employee-update',                 'employee',               'update',            'Memperbarui data pegawai'),
  ('employee-reset_password',         'employee',               'reset_password',    'Mereset password pegawai'),
  ('branch-read',                     'branch',                 'read',              'Melihat data cabang'),
  ('branch-create',                   'branch',                 'create',            'Membuat data cabang'),
  ('branch-update',                   'branch',                 'update',            'Memperbarui data cabang'),
  ('branch-delete',                   'branch',                 'delete',            'Menghapus data cabang'),
  ('department-read',                 'department',             'read',              'Melihat data department'),
  ('department-create',               'department',             'create',            'Membuat data department di department'),
  ('department-update',               'department',             'update',            'Memperbarui data department di department'),
  ('department-delete',               'department',             'delete',            'Menghapus data department di department'),
  ('job_position-read',               'job_position',           'read',              'Melihat data jabatan di department'),
  ('job_position-create',             'job_position',           'create',            'Membuat data jabatan di department'),
  ('job_position-update',             'job_position',           'update',            'Memperbarui data jabatan di department'),
  ('job_position-delete',             'job_position',           'delete',            'Menghapus data jabatan di department'),
  ('role-read',                       'role',                   'read',              'Melihat data role'),
  ('role-create',                     'role',                   'create',            'Membuat data role'),
  ('role-update',                     'role',                   'update',            'Memperbarui data role'),
  ('role-delete',                     'role',                   'delete',            'Menghapus data role'),
  ('leave_type-read',                 'leave_type',             'read',              'Melihat data jenis cuti'),
  ('leave_type-create',               'leave_type',             'create',            'Membuat data jenis cuti'),
  ('leave_type-update',               'leave_type',             'update',            'Memperbarui data jenis cuti'),
  ('leave_type-delete',               'leave_type',             'delete',            'Menghapus data jenis cuti'),
  ('template_shift-read',             'template_shift',         'read',              'Melihat data template shift'),
  ('template_shift-create',           'template_shift',         'create',            'Membuat data template shift'),
  ('template_shift-update',           'template_shift',         'update',            'Memperbarui data template shift'),
  ('template_shift-delete',           'template_shift',         'delete',            'Menghapus data template shift'),
  ('schedule-read',                   'schedule',               'read',              'Melihat data jadwal shift'),
  ('schedule-create',                 'schedule',               'create',            'Membuat data jadwal shift'),
  ('schedule-update',                 'schedule',               'update',            'Memperbarui data jadwal shift'),
  ('schedule-delete',                 'schedule',               'delete',            'Menghapus data jadwal shift'),
  ('holiday-read',                    'holiday',                'read',              'Melihat data hari libur'),
  ('holiday-create',                  'holiday',                'create',            'Membuat data hari libur'),
  ('holiday-update',                  'holiday',                'update',            'Memperbarui data hari libur'),
  ('holiday-delete',                  'holiday',                'delete',            'Menghapus data hari libur'),
  ('attendance-read',                 'attendance',             'read',              'Melihat data jadwal shift'),
  ('attendance-create',               'attendance',             'create',            'Membuat data jadwal shift'),
  ('attendance_adjustment-read',      'attendance_adjustment',  'read',              'Melihat data penyesuaian kehadiran'),
  ('attendance_adjustment-create',    'attendance_adjustment',  'create',            'Membuat data penyesuaian kehadiran'),
  ('attendance_adjustment-approve',   'attendance_adjustment',  'approve',           'Menyetujui data penyesuaian kehadiran'),
  ('leave-read',                      'leave',                  'read',              'Melihat data jenis cuti'),
  ('leave-create',                    'leave',                  'create',            'Membuat data jenis cuti'),
  ('leave-leader_approve',            'leave',                  'leader_approve',    'Menyetujui data jenis cuti'),
  ('leave-hr_approve',                'leave',                  'hr_approve',        'Menyetujui data jenis cuti'),
  ('leave_balance-read',              'leave_balance',          'read',              'Melihat data jenis cuti'),
  ('request-read',                    'request',                'read',              'Melihat data pengajuan'),
  ('request-create',                  'request',                'create',            'Membuat data pengajuan'),
  ('request-approve',                 'request',                'approve',           'Menyetujui data pengajuan'),
  ('business_trip-read',              'business_trip',          'read',              'Melihat data tugas'),
  ('business_trip-create',            'business_trip',          'create',            'Membuat data tugas'),
  ('business_trip-approve',           'business_trip',          'approve',           'Menyetujui data tugas'),
  ('overtime-read',                   'overtime',               'read',              'Melihat data lembur'),
  ('overtime-create',                 'overtime',               'create',            'Membuat data lembur'),
  ('overtime-approve',                'overtime',               'approve',           'Menyetujui data lembur'),
  ('daily_report-read',               'daily_report',           'read',              'Melihat data laporan harian'),
  ('daily_report-create',             'daily_report',           'create',            'Membuat data laporan harian'),
  ('mutabaah-read',                   'mutabaah',               'read',              'Melihat data mutabaah'),
  ('mutabaah-create',                 'mutabaah',               'create',            'Membuat data mutabaah'),
  ('profile-read',                    'profile',                'read',              'Melihat data profile'),
  ('profile-update',                  'profile',                'update',            'Memperbarui data profile'),
  ('profile-reset_password',          'profile',                'reset_password',    'Mereset kata sandi profile');
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
TRUNCATE permissions RESTART IDENTITY CASCADE;
-- +goose StatementEnd
