package service

import (
	"context"
	"fmt"
	"time"

	logger "hris-backend/config/log"
	"hris-backend/internal/repository"
	"hris-backend/internal/struct/model"
	"hris-backend/internal/utils"
)

// CronService menjalankan scheduled jobs untuk:
// 1. Menandai pegawai absent (tidak clock in, tidak punya cuti/izin)
// 2. Menandai mutabaah missing (hadir tapi tidak submit)
type CronService interface {
	RunDailyAbsentMark(ctx context.Context, date string) error
	RunDailyMutabaahMark(ctx context.Context, date string) error
	RunDailyReportMark(ctx context.Context, date string) error
	GenerateDailyPushReminders(ctx context.Context, date string) error
	SendMutabaahReminders(ctx context.Context, date string) error
	SendPendingNotifications(ctx context.Context) error
}

type cronService struct {
	attendRepo    repository.AttendanceRepository
	mutabaah      repository.MutabaahRepository
	dailyReport   repository.DailyReportRepository
	txManager     repository.TxManager
	notifSvc      NotificationService
}

func NewCronService(
	attendRepo repository.AttendanceRepository,
	mutabaah repository.MutabaahRepository,
	dailyReport repository.DailyReportRepository,
	txManager repository.TxManager,
	notifSvc NotificationService,
) CronService {
	return &cronService{
		attendRepo:  attendRepo,
		mutabaah:    mutabaah,
		dailyReport: dailyReport,
		txManager:   txManager,
		notifSvc:    notifSvc,
	}
}

// RunDailyAbsentMark — jalankan tiap malam setelah jam kerja selesai (mis. 23:59)
// Buat record attendance_logs dengan status 'absent' + is_auto_generated=true
// untuk pegawai yang punya jadwal aktif tapi tidak clock in dan tidak ada cuti/libur
func (s *cronService) RunDailyAbsentMark(ctx context.Context, date string) error {
	if date == "" {
		date = utils.TodayDate()
	}

	logger.Info("cron: start daily absent mark", map[string]any{"date": date})

	// Ambil semua pegawai yang punya jadwal aktif tapi tidak punya log
	employeeIDs, err := s.attendRepo.GetEmployeesWithActiveScheduleWithoutLog(ctx, nil, date)
	if err != nil {
		return fmt.Errorf("cron: get employees without log: %w", err)
	}

	if len(employeeIDs) == 0 {
		logger.Info("cron: no absent employees to mark", map[string]any{"date": date})
		return nil
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return fmt.Errorf("cron: parse date: %w", err)
	}

	logs := make([]model.AttendanceLog, 0, len(employeeIDs))
	skipped := 0

	for _, empID := range employeeIDs {
		// Cek hari libur per cabang pegawai
		branchID, _ := s.attendRepo.GetEmployeeBranchID(ctx, nil, empID)
		isHoliday, _, _ := s.attendRepo.IsHoliday(ctx, nil, branchID, date)
		if isHoliday {
			skipped++
			continue
		}

		// Cek cuti yang disetujui — kalau ada cuti, buat log dengan status leave
		leaveID, _ := s.attendRepo.GetApprovedLeave(ctx, nil, empID, date)
		tripID, _ := s.attendRepo.GetApprovedBusinessTrip(ctx, nil, empID, date)

		var status model.AttendanceStatusEnum
		var leaveRequestID *uint
		var businessTripID *uint

		switch {
		case leaveID != nil:
			status = model.AttendanceLeave
			leaveRequestID = leaveID
		case tripID != nil:
			status = model.AttendanceBusinessTrip
			businessTripID = tripID
		default:
			status = model.AttendanceAbsent
		}

		// Ambil schedule ID
		shift, _ := s.attendRepo.GetActiveSchedule(ctx, nil, empID, date)
		var scheduleID *uint
		if shift != nil {
			scheduleID = &shift.ScheduleID
		}

		logs = append(logs, model.AttendanceLog{
			EmployeeID:            empID,
			ScheduleID:            scheduleID,
			AttendanceDate:        parsedDate,
			Status:                status,
			LeaveRequestID:        leaveRequestID,
			BusinessTripRequestID: businessTripID,
			IsAutoGenerated:       true,
			IsCountedAsFullDay:    false,
		})
	}

	if len(logs) == 0 {
		logger.Info("cron: all employees have leave/holiday, no absent to mark", map[string]any{
			"date":    date,
			"skipped": skipped,
		})
		return nil
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return fmt.Errorf("cron: begin tx: %w", err)
	}
	defer tx.Rollback()

	if err := s.attendRepo.BulkCreateAbsentLogs(ctx, tx, logs); err != nil {
		return fmt.Errorf("cron: bulk create absent logs: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cron: commit: %w", err)
	}

	logger.Info("cron: daily absent mark completed", map[string]any{
		"date":    date,
		"marked":  len(logs),
		"skipped": skipped,
	})

	// Trigger absent alerts for marked absent employees
	for _, log := range logs {
		if log.Status == model.AttendanceAbsent {
			if err := s.notifSvc.TriggerAbsentAlert(ctx, log.EmployeeID, date); err != nil {
				logger.Error("cron: failed to trigger absent alert", map[string]any{
					"employee_id": log.EmployeeID,
					"date":        date,
					"error":       err.Error(),
				})
			}
		}
	}

	return nil
}

// RunDailyMutabaahMark — jalankan setelah RunDailyAbsentMark
// Buat record mutabaah_logs dengan is_submitted=false + is_auto_generated=true
// untuk pegawai yang hadir (present/late) tapi tidak submit mutabaah
func (s *cronService) RunDailyMutabaahMark(ctx context.Context, date string) error {
	if date == "" {
		date = utils.TodayDate()
	}

	logger.Info("cron: start daily mutabaah mark", map[string]any{"date": date})

	rows, err := s.mutabaah.GetEmployeesWithAttendanceWithoutMutabaah(ctx, nil, date)
	if err != nil {
		return fmt.Errorf("cron: get employees without mutabaah: %w", err)
	}

	if len(rows) == 0 {
		logger.Info("cron: no missing mutabaah to mark", map[string]any{"date": date})
		return nil
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return fmt.Errorf("cron: parse date: %w", err)
	}

	logs := make([]model.MutabaahLog, 0, len(rows))
	for _, row := range rows {
		attID := row.AttendanceLogID
		logs = append(logs, model.MutabaahLog{
			EmployeeID:      row.EmployeeID,
			AttendanceLogID: &attID,
			LogDate:         parsedDate,
			TargetPages:     0,
			IsSubmitted:     false,
			IsAutoGenerated: true,
		})
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return fmt.Errorf("cron: begin tx: %w", err)
	}
	defer tx.Rollback()

	if err := s.mutabaah.BulkCreateMissingLogs(ctx, tx, logs); err != nil {
		return fmt.Errorf("cron: bulk create missing mutabaah: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cron: commit: %w", err)
	}

	logger.Info("cron: daily mutabaah mark completed", map[string]any{
		"date":   date,
		"marked": len(logs),
	})
	return nil
}

// RunDailyReportMark — create unsubmitted daily report for employees present but didn't submit
func (s *cronService) RunDailyReportMark(ctx context.Context, date string) error {
	if date == "" {
		date = utils.TodayDate()
	}

	logger.Info("cron: start daily report mark", map[string]any{"date": date})

	rows, err := s.dailyReport.GetEmployeesWithAttendanceWithoutDailyReport(ctx, nil, date)
	if err != nil {
		return fmt.Errorf("cron: get employees without daily report: %w", err)
	}

	if len(rows) == 0 {
		logger.Info("cron: no missing daily reports to mark", map[string]any{"date": date})
		return nil
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return fmt.Errorf("cron: parse date: %w", err)
	}

	logs := make([]model.DailyReport, 0, len(rows))
	for _, row := range rows {
		logs = append(logs, model.DailyReport{
			EmployeeID:      row.EmployeeID,
			AttendanceLogID: row.AttendanceLogID,
			ReportDate:      parsedDate,
			IsSubmitted:     false,
			IsAutoGenerated: true,
		})
	}

	tx, err := s.txManager.Begin(ctx)
	if err != nil {
		return fmt.Errorf("cron: begin tx: %w", err)
	}
	defer tx.Rollback()

	if err := s.dailyReport.BulkCreateMissingLogs(ctx, tx, logs); err != nil {
		return fmt.Errorf("cron: bulk create missing daily reports: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("cron: commit: %w", err)
	}

	logger.Info("cron: daily report mark completed", map[string]any{
		"date":   date,
		"marked": len(logs),
	})
	return nil
}

// GenerateDailyPushReminders — generate clock in/out reminders untuk besok
func (s *cronService) GenerateDailyPushReminders(ctx context.Context, date string) error {
	tomorrow := utils.TodayDate()
	logger.Info("cron: generate daily push reminders", map[string]any{"date": tomorrow})

	// Get all employees with active schedule tomorrow
	employeeIDs, err := s.attendRepo.GetEmployeesWithActiveScheduleWithoutLog(ctx, nil, tomorrow)
	if err != nil {
		return fmt.Errorf("cron: get employees with schedule: %w", err)
	}

	for _, empID := range employeeIDs {
		shift, err := s.attendRepo.GetActiveSchedule(ctx, nil, empID, tomorrow)
		if err != nil || shift == nil || !shift.IsWorkingDay {
			continue
		}

		// Clock in reminder (10 min before clock_in_end)
		if shift.ClockInEnd != nil {
			if err := s.notifSvc.TriggerClockInReminder(ctx, empID, tomorrow, *shift.ClockInEnd); err != nil {
				logger.Error("cron: clock in reminder failed", map[string]any{
					"employee_id": empID,
					"error":       err.Error(),
				})
			}
		}

		// Clock out reminder (10 min before clock_out_end)
		if shift.ClockOutEnd != nil {
			if err := s.notifSvc.TriggerClockOutReminder(ctx, empID, tomorrow, *shift.ClockOutEnd); err != nil {
				logger.Error("cron: clock out reminder failed", map[string]any{
					"employee_id": empID,
					"error":       err.Error(),
				})
			}
		}
	}

	logger.Info("cron: daily push reminders generated", map[string]any{
		"date":     tomorrow,
		"employees": len(employeeIDs),
	})
	return nil
}

// SendMutabaahReminders — kirim reminder mutabaah ke pegawai yang belum submit
func (s *cronService) SendMutabaahReminders(ctx context.Context, date string) error {
	logger.Info("cron: send mutabaah reminders", map[string]any{"date": date})

	if err := s.notifSvc.SendMutabaahReminders(ctx, date); err != nil {
		return fmt.Errorf("cron: send mutabaah reminders: %w", err)
	}

	logger.Info("cron: mutabaah reminders sent", map[string]any{"date": date})
	return nil
}

// SendPendingNotifications — polling DB setiap menit untuk kirim push pending
func (s *cronService) SendPendingNotifications(ctx context.Context) error {
	return s.notifSvc.SendPendingNotifications(ctx)
}
